export const ACTION_NOT_VERIFIED = 'ACTION_NOT_VERIFIED';
export const TYPE_FAILED = 'TYPE_FAILED';
export const NO_EFFECT = 'NO_EFFECT';
export const LOADING_PENDING = 'LOADING_PENDING';
export const EXECUTION_FAILED = 'EXECUTION_FAILED';
export const ROUTE_BLOCKED = 'ROUTE_BLOCKED';
export const BOUNDARY_MISMATCH = 'BOUNDARY_MISMATCH';
